### ISSUE TITLE
README is incomplete!

### ISSUE THREAD

**Issue by r9host** [serfreeman1337/asterlink#1]
README does not describe how to install Asterlink on FreePBX. It is written in GoLang but FreePBX is based on PHP.

**Comment by serfreeman1337** [comment]
I'm planning to create install script.

Here is manual install instructions for FreePBX Distro to install asterlink under **/opt/asterlink** folder.

* Create folder /opt/asterlink
  ```bash
  mkdir /opt/asterlink; cd /opt/asterlink
  ```
* Download binary from [Releases page](https://github.com/serfreeman1337/asterlink/releases)
  ```bash
  wget https://github.com/serfreeman1337/asterlink/releases/download/v0.1.0/asterlink_x86_64.tar.gz
  ```
* Extract binary and make it executable
  ```bash
  tar xvf asterlink_x86_64.tar.gz && rm asterlink_x86_64.tar.gz
  chmod +x asterlink
  ```
* Create configuration file. Use conf.example.yml as example.
  ```bash
  wget https://raw.githubusercontent.com/serfreeman1337/asterlink/master/conf.example.yml
  mv conf.example.yml conf.yml
  nano conf.yml
  ```
* Test run
  ```bash
  ./asterlink
  ```

Startup script example.
**/etc/systemd/system/asterlink.service**
```
[Unit]
Description=AsterLink Connector
After=freepbx.service

[Install]
WantedBy=multi-user.target

[Service]
ExecStart=/bin/sh -c 'exec /opt/asterlink/asterlink >>/opt/asterlink/app.log 2>>/opt/asterlink/err_app.log'
WorkingDirectory=/opt/asterlink
Restart=always
RestartSec=5
```
```bash
systemctl enable asterlink
systemctl start asterlink
```

You can also [build binary from source](https://www.digitalocean.com/community/tutorials/how-to-build-and-install-go-programs).

**Comment by r9host** [comment]
Thank you for your reply. The binary cannot be executed on my box as it is a Raspberry Pi based on the ARM processor. I'm trying to build from scratch but I get this error: "../../sirupsen/logrus/terminal_check_unix.go:6:8: cannot find package "golang.org/x/sys/unix" and "go get golang.org/x/sys/unix" fails with error: "no go-import meta tags"

**Comment by serfreeman1337** [comment]
Try to run **go get**:
```
set GOOS=linux
set GOARCH=arm
go get
go build
```

**Comment by r9host** [comment]
:( Still cannot get "golang.org/x/sys/unix" dependency.

**Comment by serfreeman1337** [comment]
If you are trying to compile it on windows:

Try remove to remove **%GOPATH%\src\golang.org\x** and run **go get** again.
```
go clean -i -cache -x -r
rd /s /q "%GOPATH%/src/golang.org/x"
set GOOS=linux
set GOARCH=arm
go get
go build
```

please, create new issue

**Comment by Go0dwInD** [comment]
Good afternoon, is it possible to write a more detailed readme. Describe the setting for Diaplan in more detail. For Dummies.
