### ISSUE TITLE
The clicktocall window does not appear. 

### ISSUE THREAD

**Issue by MatthewWeb** [serfreeman1337/asterlink#14]
![изображение](https://user-images.githubusercontent.com/56957860/208678662-2b1bb478-92e6-4d23-86f4-810246843eb4.png)
![изображение](https://user-images.githubusercontent.com/56957860/208679874-89ec4b4c-5bd1-4626-82ea-643da44ff013.png)
![изображение](https://user-images.githubusercontent.com/56957860/208680236-b61952a3-b4da-4d1d-8e75-5baf06cc1f45.png)
![изображение](https://user-images.githubusercontent.com/56957860/208680358-daa5475f-2824-43d7-94aa-d84fc5e3aa5d.png)

In asterisk ami there is also no empty space.

**Comment by MatthewWeb** [comment]
Yes

**Comment by serfreeman1337** [comment]
What about `curl -v http://127.0.0.1:5678/ws/` on the asterlink machine ?

**Comment by MatthewWeb** [comment]
*   Trying 127.0.0.1:5678...
* Connected to 127.0.0.1 (127.0.0.1) port 5678 (#0)
> GET /ws/ HTTP/1.1
> Host: 127.0.0.1:5678
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Tue, 20 Dec 2022 15:36:42 GMT
< Server: Apache
< Vary: accept-language,accept-charset
< Accept-Ranges: bytes
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=utf-8
< Content-Language: en
< 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Object not found!</title>
<link rev="made" href="mailto:%5bno%20address%20given%5d" />
<style type="text/css"><![CDATA[/*></style>
</head>

<body>
<h1>Object not found!</h1>
<p>

**Comment by MatthewWeb** [comment]
![изображение](https://user-images.githubusercontent.com/56957860/208706090-5af8d4ce-accd-4c2c-8e49-283af9df9778.png)
![изображение](https://user-images.githubusercontent.com/56957860/208706528-7542a71d-7896-4db3-8d2d-d27079e7b896.png)

I don't have this option. That's probably the point.

**Comment by serfreeman1337** [comment]
That's apache webserver on this port which is weird.
Is `./asterlink` process really running on the 5678 port ?

As I see from first screenshot, `Enabling web server addr="0.0.0.0:5678"` means 5678 tcp port is listening by asterlink process and there is no way apache whould bind to that address. 

Do you run asterlink process and suitecrm on separate machines ?

**Comment by MatthewWeb** [comment]
Yes

**Comment by serfreeman1337** [comment]
On suitecrm module's settings page in `Endpoint URL` and `WebSocket URL` fields 
you need to specify ip of machine **where asterlink process is running**.

You can also try to use another port like 51034:
conf.yml:
```
   endpoint_addr: "0.0.0.0:51034"
```
Then update port on module's settings page as well.

**Comment by MatthewWeb** [comment]
![изображение](https://user-images.githubusercontent.com/56957860/208722952-5bc4a948-20ad-49ab-9d7d-ce88aed1d984.png)
There is some progress. But there is still no clicktocall window

**Comment by serfreeman1337** [comment]
Please show browser console when you click on a number. (as I see on 2-nd screen, click2call tries to send dial request)

**Comment by MatthewWeb** [comment]
![изображение](https://user-images.githubusercontent.com/56957860/208729635-8cc5f8cd-edb2-472b-b490-2bc3d97555a4.png)

**Comment by serfreeman1337** [comment]
I see click2call request was successfully sent. You shoud get a popup card once you receive call on 999 extension. (click2call first rings user extension and after answer asterisk will dial clicked number)

**Comment by MatthewWeb** [comment]
![изображение](https://user-images.githubusercontent.com/56957860/208828573-75a3b9b0-0c20-42ed-b84d-167087249620.png)
Everything is fine. It remains to configure dialplan.
The last question, through https can I somehow make it work? Swears at the certificate.

**Comment by serfreeman1337** [comment]
You need to use domain instead of ip for https.

**Comment by MatthewWeb** [comment]
![изображение](https://user-images.githubusercontent.com/56957860/208854896-0ca149d3-a0df-4e70-abc0-fd4b5302b1d1.png)
![изображение](https://user-images.githubusercontent.com/56957860/208855216-2c219f07-5cf2-41c3-8641-46a0394d88b7.png)
![изображение](https://user-images.githubusercontent.com/56957860/208855979-abf35ba6-8af8-4e5d-9a82-fb792c5e2eea.png)
I'll deal with ssl later. Dialplan does not accept. The call goes through telnet.

**Comment by serfreeman1337** [comment]
dial-context in conf.yml is the click2call context to place calls.
In your setup it should be:
```
  dial_context: clall-out
```
[Note that asterlink higly relies on dialplan. ](https://github.com/serfreeman1337/asterlink#asterisk)
Check [basic-pbx](https://github.com/asterisk/asterisk/blob/master/configs/basic-pbx/extensions.conf) dialplan example.

**Comment by MatthewWeb** [comment]
Thanks a lot! Everything worked out and the calls went! 
Thanks for your hard work!
