### ISSUE TITLE
Filtering incoming calls from FreePBX | Outgoing calls not being triggered

### ISSUE THREAD

**Issue by EfimSirotkin** [serfreeman1337/asterlink#15]
Hi! I'm kind of confused on how to filter specific numbers for incoming calls. I get notifications on every incoming call that is being registered in my incoming context, but I want to be able to limit the numbers that are actually processed by Asterlink. Is there a way to make it work? I've seen the regexp example and tried it a little, but with no success. Thanks in advance!

Also I'm facing another issue right now and also I don't even know how to debug it, because I don't get log entries while performing click to call from Bitrix24 UI. The point is that when I manually perform outgoing call by typing a number I get the record a call uploaded but I'm not able to call from the Bitrix card straight.
Can you please give me some hints on resolving that issues? Thanks!

**Comment by EfimSirotkin** [comment]
Ah, man... The problem with DID was due to incorrect identation.. Fixed it. Now it's working!!! Thanks!

But still. Handler URL is accessible from bitrix server. So these are 3 separate VMs that are located in one local subnet. So they're accessible to each other. Don't know what to do. I've tested using curl and when I do it manually it does work, but Bitrix doesn't perform it.

Maybe the issue it because of incorrect dialplan configuration. Kind of a dummy here.
![image](https://github.com/serfreeman1337/asterlink/assets/44836472/e2924b6f-231f-4e00-83f7-cf144bba70f7)

**Comment by EfimSirotkin** [comment]
Yeah, everything is quite right, dialer shows "Application: Outbound webhook".. How can I manully trigger an outgoing call with curl from Bitrix. Maybe there is a template for it so I can build my own request and test it to exclude the problem with firewalls between VMs.

**Comment by EfimSirotkin** [comment]
It seems kind of confusing to me, because I have Yealink telephones connected and registered at FreePBX and I can't imagine how the outgoing call will be triggered that way. Should I have softphone software configured instead?? Also there is a functionality to configure internal telephony in Bitrix24 and connect telephones there via ip.bitrix-xxxx.telephony.com. Should we configure it to make things work?

**Comment by serfreeman1337** [comment]
> How can I manully trigger an outgoing call with curl from Bitrix.
```bash
curl -v --location 'http://newbitfreepbx.rrb.by:56789/originate/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'auth%5Bapplication_token%5D=APPLICATION_TOKEN' \
--data-urlencode 'data%5BUSER_ID%5D=1' \
--data-urlencode 'data%5BPHONE_NUMBER_INTERNATIONAL%5D=+375291234567' \
--data-urlencode 'data%5BCALL_ID%5D=SOME_RANDOM_VALUE'
```



>  Because I have Yealink telephones connected and registered at FreePBX and I can't imagine how the outgoing call will be triggered that way

It was just my guess about your setup, because you said that your employee have a number that looks like a public one. 

> I listed 2 numbers. The first one - is the number of a "client" that is performing incoming call.
> And the second one - is the number of a employee that the call is intended to come to.

Oh wait, I get it now. Employee number is the DID and you wanted asterlink to only registers calls for this DID.

**Comment by EfimSirotkin** [comment]
Yeah, we have progress with manual curl, but it seems that Asterlink can't find extension.. I have no idea what extension should be used and where it should be configured.

![image](https://github.com/serfreeman1337/asterlink/assets/44836472/05f1e602-f2ac-459e-b582-7e7d85687953)

So the user with ID=1 has internal extension = 4444 and the work_phone +37517xxxxxxx, I'm trying to call to +37529yyyyyy, but it shows me these errors.

P.S. Russian is not a problem :)

**Comment by EfimSirotkin** [comment]
So the curl format is as follows: 
![image](https://github.com/serfreeman1337/asterlink/assets/44836472/401d8fa2-cbe3-4480-bf7e-d7fa18a5c1f0)

**Comment by serfreeman1337** [comment]
> P.S. Russian is not a problem :)
> Extension does not exists.

Это ответ на Originate от Asterisk.  Либо нету внутреннего экстеншена 4444, либо нету исходящего маршрута для номера `+375X.`. Оба номера набираются в контексте [from-internal](https://github.com/serfreeman1337/asterlink/blob/23b855a80b41fab22accb722ec48999ac02ed6be/conf.example.yml#L16).

**Comment by EfimSirotkin** [comment]
А outgoing_context тоже тогда должен быть from-internal?

вт, 27 июн. 2023 г., 19:08 serfreeman1337 ***@***.***>:

**Comment by serfreeman1337** [comment]
В outgoing_context регистрируются исходящие вызовы, т.е. там должен быть
контекст, через который набирается только транк. from-internal - общий
контекст, где набираются еще и внутр. экстеншены.

**Comment by EfimSirotkin** [comment]
Добрый день! Спасибо за все ответы. А может ли быть такое, что он не
находит маршрут для этого extension из-за неверного outgoing_context?


вт, 27 июн. 2023 г., 21:55 serfreeman1337 ***@***.***>:

**Comment by EfimSirotkin** [comment]
Исходящий маршрут для этого экстеншена существует и при наборе номера +37529ххх вручную все отлично, однако при попытке сделать это через curl пишет, что extension does not exist.
![image](https://github.com/serfreeman1337/asterlink/assets/44836472/b41c1a2f-18a1-4160-b277-89bdaadca3a4)

**Comment by serfreeman1337** [comment]
Можно попробовать убрать 4444 в маршруте для теста.
`asterisk -rx "dialplan show ext-local" | grep 4444` - тут 4444 же есть ?

**Comment by EfimSirotkin** [comment]
Да, вывод есть.
![image](https://github.com/serfreeman1337/asterlink/assets/44836472/34cbe91b-3780-44d9-9ce9-1cd0a0fadcca)

**Comment by serfreeman1337** [comment]
dial_context в conf.yml же `from-internal` ?

Может быть asterisk не пропускает из-за ограничения по 4444 CallerID (4 поле) в исходящем маршруте. Если возможно, можно  попробовать временно убрать это ограничение и проверить еще раз. Но у меня на freepbx14 работало и так.

А через консоль `asterisk -rvvvvv` тоже можно вызвать 4444, например в эхо-тест?
`channel originate Local/4444@from-internal application Echo`

**Comment by EfimSirotkin** [comment]
Изменил dial_context на from-internal - стал инициировать звонок (по логу видно), но выдает Bad Request по истечении примерно 10 секунд после New Originate request. 
![image](https://github.com/serfreeman1337/asterlink/assets/44836472/bd049f51-0411-40cc-995b-996aa71d969a)
Отправляю вот такой запрос, при этом у 4444 id = 1. вроде все ок.
![image](https://github.com/serfreeman1337/asterlink/assets/44836472/0322631d-0971-49da-8f89-4c6e9f47361d)
вот что curl отдает в консоль: 
![image](https://github.com/serfreeman1337/asterlink/assets/44836472/2380be45-e92d-418f-bf6e-3ec5713a6842)


Эхо-тест, кстати, отрабатывает. Звонок приходит

**Comment by serfreeman1337** [comment]
Этот `400 Bad Request` от битрикса, может быть он ожидает существующий oID.
Главное что номер теперь набирается через curl и что проблема была в conf.yml:
> Изменил dial_context на from-internal - стал инициировать звонок

Если починить исходящие вебхуки, то набор номера из битрикса должен заработать.
Как я понял, в коробочной версии исходящие вебхуки работают через официальный сервер, в ссылке из этого коммента есть информация про это: https://github.com/serfreeman1337/asterlink/issues/15#issuecomment-1609609383

У меня нету коробочной версии и проверить этот момент не могу.

**Comment by EfimSirotkin** [comment]
Добрый день! Спасибо большое за ответы! Прокинул сервак вовне и заработало через внешку.
