### ISSUE TITLE
Lead is always named as "Missed Call"

### ISSUE THREAD

**Issue by r9host** [serfreeman1337/asterlink#3]
Even when the call is successful and is answered by softphone, the lead is titled as "Пропущенный звонок" which means "Missed call". However, the employee in Bitrix24 is detected properly.

**Comment by serfreeman1337** [comment]
Does call card has been displayed for operator in CRM ?
If yes, check asterlink logs, does "**msg="Call finished"**" log happens before the actual operator answer ?

I need some info about your setup:
FreePBX and Asterisk version:
```
fwconsole -V
asterisk -rx "core show version"
```
Do you have "Follow me" enabled or any 3rd party modules, which affects default freepbx dialplan ?

<details>
  <summary>AMI events dump</summary>

  On Linux it's can be done with
  ```bash
  telnet 127.0.0.1 5038 | tee -i session-recording.log
  ```
  then paste:
  ```
  Action: Login
  Username: your_ami_user
  Secret: your_ami_password
  
  ```
  you will get:
  ![image](https://user-images.githubusercontent.com/2133936/72684096-a69a9f00-3aee-11ea-994f-87bd93d2ab03.png)
  make a call and after you finish paste:
  ```
  Action: Logoff
  
  ```

  **AMI dump can contain some private info, like CallerID and DID numbers.**
  You can send it to my email: serfreeman1337 (from) yandex com
</details>
